# working directory
dir: "/vol/cluster-data/rchen/git/ms_female_ltet"

# path to output directory
output_dir: "/vol/cluster-data/rchen/git/ms_female_ltet/output"

# input directory where raw reads are
input_dir: "/vol/cluster-data/rchen/wgr/females/BMK250613-CQ027-ZX01-0101/BMK_DATA_20260330132240_1/"

# file from BMK with their vs my names of samples
BMK_names: "/vol/cluster-data/rchen/wgr/females/BMK250613-CQ027-ZX01-0101/BMK_DATA_20260330132240_1/sampleName_clientId_first2.txt"

# tmp location 
tmpdir: "/grp/molecol/rchen/temp"

# reference genome 
ref_gen: "/vol/cluster-data/rchen/annotation/PO2979_Lyrurus_tetrix_black_grouse.RepeatMasked.fasta"
